<?php

namespace SEPBundle\Repository;

/**
 * BatchAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BatchAssignmentRepository extends \Doctrine\ORM\EntityRepository
{
}
